name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The value of the version to be released"
        required: true
        default: "Ex: 5.4.0.Final"
        type: string
      next_development_version:
        description: "The value of the next version to be developed"
        required: true
        default: "Ex: 5.4.1-SNAPSHOT"
        type: string
      previous_version:
        description: The tag to compare against the release tag. Use to generate the "changelog"
        required: false
        default: 5.3.0.Final
        type: string

jobs:
  windup:
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-rulesets:
    needs: [windup]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-rulesets
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-distribution:
    needs: [windup-rulesets]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-distribution
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/windup-distribution.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-web-before:
    needs: [windup-distribution]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${RELEASE_VERSION}<\/version.windup>/g" pom.xml
          git add pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${RELEASE_VERSION}<\/version.windup.core>/g" tsmodelsgen-invocation/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${RELEASE_VERSION}<\/version.windup.web>/g" tsmodelsgen-invocation/pom.xml
          git add tsmodelsgen-invocation/pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${RELEASE_VERSION}<\/version.windup.core>/g" tsmodelsgen-maven-plugin/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${RELEASE_VERSION}<\/version.windup.web>/g" tsmodelsgen-maven-plugin/pom.xml
          git add tsmodelsgen-maven-plugin/pom.xml

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

          git commit --allow-empty -a -m "Preparing for release"
          git push origin HEAD:master
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-web:
    needs: [windup-web-before]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-web
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-web-after:
    needs: [windup-web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${NEXT_DEVELOPMENT_VERSION}<\/version.windup>/g" pom.xml
          git add pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.core>/g" tsmodelsgen-invocation/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.web>/g" tsmodelsgen-invocation/pom.xml
          git add tsmodelsgen-invocation/pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.core>/g" tsmodelsgen-maven-plugin/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.web>/g" tsmodelsgen-maven-plugin/pom.xml
          git add tsmodelsgen-maven-plugin/pom.xml

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

          git commit --allow-empty -a -m "Back to development"
          git push origin HEAD:master
        env:
          NEXT_DEVELOPMENT_VERSION: ${{ github.event.inputs.next_development_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-openshift-before:
    needs: [windup-web-after]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-openshift
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/\"DOCKER_IMAGES_TAG\"/\"${RELEASE_VERSION}\"/g" templates/src/main/resources/web-template-empty-dir-executor.json
          git add templates/src/main/resources/web-template-empty-dir-executor.json

          sed -i -e "s/\"DOCKER_IMAGES_TAG\"/\"${RELEASE_VERSION}\"/g" templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json
          git add templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

          git commit --allow-empty -a -m "Preparing for release"
          git push origin HEAD:master
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-openshift:
    needs: [windup-openshift-before]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-openshift
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-openshift-after:
    needs: [windup-openshift]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-openshift
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/\"DOCKER_IMAGES_TAG\"/\"${NEXT_DEVELOPMENT_VERSION}\"/g" templates/src/main/resources/web-template-empty-dir-executor.json
          git add templates/src/main/resources/web-template-empty-dir-executor.json

          sed -i -e "s/\"DOCKER_IMAGES_TAG\"/\"${NEXT_DEVELOPMENT_VERSION}\"/g" templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json
          git add templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"      

          git commit --allow-empty -a -m "Back to development"
          git push origin HEAD:master
        env:
          NEXT_DEVELOPMENT_VERSION: latest
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-openshift-container-images:
    needs: [windup-openshift-after]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-openshift
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.release_version }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
      - name: Create container images
        run: |
          mvn install -DskipTests \
          -Ddocker.name.windup.web=quay.io/carlosthe19916/windup-web-openshift:$TAG \
          -Ddocker.name.windup.web.executor=quay.io/carlosthe19916/windup-web-openshift-messaging-executor:$TAG \
          -Ddocker.name.windup.cli=quay.io/carlosthe19916/windup-cli-openshift:$TAG
        env:
          TAG: ${{ github.event.inputs.release_version }}
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
      - name: Push images to registry
        run: |
          docker image push --all-tags quay.io/carlosthe19916/windup-web-openshift
          docker image push --all-tags quay.io/carlosthe19916/windup-web-openshift-messaging-executor
          docker image push --all-tags quay.io/carlosthe19916/windup-cli-openshift

  windup-web-distribution:
    needs: [windup-openshift-container-images]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-web-distribution
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-maven-plugin-before:
    needs: [windup-web-distribution]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-maven-plugin
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${RELEASE_VERSION}<\/version.windupcore>/g" pom.xml
          git add pom.xml

          sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${RELEASE_VERSION}<\/version.windupcore>/g" src/it/simple-it/pom.xml
          sed -i -e "s/<version>.*<\/version>/<version>${RELEASE_VERSION}<\/version>/g" src/it/simple-it/pom.xml
          git add src/it/simple-it/pom.xml

          sed -i -e "s/<version>.*<\/version>/<version>${RELEASE_VERSION}<\/version>/g" src/test/resources/mojoTestConfig.xml
          git add src/test/resources/mojoTestConfig.xml

          sed -i -e "s/<windupVersion>.*<\/windupVersion>/<windupVersion>${RELEASE_VERSION}<\/windupVersion>/g" src/test/resources/mojoTestConfigWithWindupVersion.xml
          git add src/test/resources/mojoTestConfigWithWindupVersion.xml

          sed -i -e "s/assertEquals(mojo2.getWindupVersion(), \".*\");/assertEquals(mojo2.getWindupVersion(), \"${RELEASE_VERSION}\");/g" src/test/java/org/jboss/windup/plugin/WindupMojoTest.java
          git add src/test/java/org/jboss/windup/plugin/WindupMojoTest.java

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

          git commit --allow-empty -a -m "Preparing for release"
          git push origin HEAD:master
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-maven-plugin:
    needs: [windup-maven-plugin-before]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-maven-plugin
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-maven-plugin-after:
    needs: [windup-maven-plugin]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-maven-plugin
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${NEXT_DEVELOPMENT_VERSION}<\/version.windupcore>/g" pom.xml
          git add pom.xml

          sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${NEXT_DEVELOPMENT_VERSION}<\/version.windupcore>/g" src/it/simple-it/pom.xml
          sed -i -e "s/<version>.*<\/version>/<version>${NEXT_DEVELOPMENT_VERSION}<\/version>/g" src/it/simple-it/pom.xml
          git add src/it/simple-it/pom.xml

          sed -i -e "s/<version>.*<\/version>/<version>${NEXT_DEVELOPMENT_VERSION}<\/version>/g" src/test/resources/mojoTestConfig.xml
          git add src/test/resources/mojoTestConfig.xml

          sed -i -e "s/<windupVersion>.*<\/windupVersion>/<windupVersion>${NEXT_DEVELOPMENT_VERSION}<\/windupVersion>/g" src/test/resources/mojoTestConfigWithWindupVersion.xml
          git add src/test/resources/mojoTestConfigWithWindupVersion.xml

          sed -i -e "s/assertEquals(mojo2.getWindupVersion(), \".*\");/assertEquals(mojo2.getWindupVersion(), \"${NEXT_DEVELOPMENT_VERSION}\");/g" src/test/java/org/jboss/windup/plugin/WindupMojoTest.java
          git add src/test/java/org/jboss/windup/plugin/WindupMojoTest.java

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"      

          git commit --allow-empty -a -m "Back to development"
          git push origin HEAD:master
        env:
          NEXT_DEVELOPMENT_VERSION: ${{ github.event.inputs.next_development_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-quickstarts-before:
    needs: [windup-maven-plugin-after]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-quickstarts
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          find . -name pom.xml -exec sed -i -e "s/${MVN_VERSION}/${RELEASE_VERSION}/g" {} \;
          git add -A

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

          git commit --allow-empty -a -m "Preparing for release"
          git push origin HEAD:master
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-quickstarts:
    needs: [windup-quickstarts-before]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-quickstarts
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

  windup-quickstarts-after:
    needs: [windup-quickstarts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-quickstarts
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          find . -name pom.xml -exec sed -i -e "s/${RELEASE_VERSION}/${NEXT_DEVELOPMENT_VERSION}/g" {} \;
          git add -A

          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"      

          git commit --allow-empty -a -m "Back to development"
          git push origin HEAD:master
        env:
          NEXT_DEVELOPMENT_VERSION: ${{ github.event.inputs.next_development_version }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
