name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The value of the version to be released"
        required: true
        default: "Ex: 5.4.0.Final"
        type: string
      next_development_version:
        description: "The value of the next version to be developed"
        required: true
        default: "Ex: 5.4.1-SNAPSHOT"
        type: string
      previous_version:
        description: The tag to compare against the release tag. Use to generate the "changelog"
        required: false
        default: 5.3.0.Final
        type: string

jobs:
  windup:
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-rulesets:
    needs: [windup]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-rulesets
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-distribution:
    needs: [windup-rulesets]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-distribution
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/windup-distribution.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-web-before:
    needs: [windup-distribution]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${RELEASE_VERSION}<\/version.windup>/g" pom.xml
          git add pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${RELEASE_VERSION}<\/version.windup.core>/g" tsmodelsgen-invocation/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${RELEASE_VERSION}<\/version.windup.web>/g" tsmodelsgen-invocation/pom.xml
          git add tsmodelsgen-invocation/pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${RELEASE_VERSION}<\/version.windup.core>/g" tsmodelsgen-maven-plugin/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${RELEASE_VERSION}<\/version.windup.web>/g" tsmodelsgen-maven-plugin/pom.xml
          git add tsmodelsgen-maven-plugin/pom.xml

          git config --global user.email "carlosthe19916@gmail.com"
          git config --global user.name "Carlos Feria"

          git commit --allow-empty -a -m "Preparing for release"
          git push origin HEAD:master
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}

  windup-web:
    needs: [windup-web-before]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-web
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-web-after:
    needs: [windup-web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      - name: Set versions
        run: |
          sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${NEXT_DEVELOPMENT_VERSION}<\/version.windup>/g" pom.xml
          git add pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.core>/g" tsmodelsgen-invocation/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.web>/g" tsmodelsgen-invocation/pom.xml
          git add tsmodelsgen-invocation/pom.xml

          sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.core>/g" tsmodelsgen-maven-plugin/pom.xml
          sed -i -e "s/<version.windup.web>.*<\/version.windup.web>/<version.windup.web>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.web>/g" tsmodelsgen-maven-plugin/pom.xml
          git add tsmodelsgen-maven-plugin/pom.xml

          git config --global user.email "carlosthe19916@gmail.com"
          git config --global user.name "Carlos Feria"

          git commit --allow-empty -a -m "Back to development"
          git push origin HEAD:master
        env:
          NEXT_DEVELOPMENT_VERSION: ${{ github.event.inputs.next_development_version }}

  windup-openshift:
    needs: [windup-web-after]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-openshift
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-web-distribution:
    needs: [windup-openshift]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-web-distribution
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-maven-plugin:
    needs: [windup-web-distribution]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-maven-plugin
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-quickstarts:
    needs: [windup-maven-plugin]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: carlosthe19916
      repository: windup-quickstarts
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      previous_version: ${{ github.event.inputs.previous_version }}
      jreleaser_file: jreleaser/basic.yml
    secrets:
      GITHUB_PAT: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
