name: Snapshots Tackle

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  tackle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: mrizzi/windup
          ref: eclipse-org.osgi.service.prefs-fix
          path: windup
      - uses: actions/checkout@v3
        with:
          repository: windup/windup-rulesets
          path: windup-rulesets
      - uses: actions/checkout@v3
        with:
          repository: windup/windup-distribution
          path: windup-distribution

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build
        run: |
          # Change groupId
          find windup-distribution/ -name "pom.xml" | xargs sed -i '0,/mta-cli/{s/<artifactId>mta-cli<\/artifactId>/<artifactId>tackle-cli<\/artifactId>/g}'

          mvn install -DskipTests -f windup
          mvn install -DskipTests -f windup-rulesets
          mvn install -DskipTests -f windup-distribution
      - name: OSSRH Snapshot
        working-directory: windup-distribution
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
