name: Windup Themes

on:
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Install JDK
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11

      # Windup
      - uses: actions/checkout@v3
        with:
          repository: mrizzi/windup
          path: windup
          ref: eclipse-org.osgi.service.prefs-fix # To avoid the Eclipse bug
      - working-directory: windup
        run: mvn install -DskipTests -Ddownstream=tackle
      # Windup rulesets
      - uses: actions/checkout@v3
        with:
          repository: windup/windup-rulesets
          path: windup-rulesets
      - working-directory: windup-rulesets
        run: mvn install -DskipTests -Ddownstream=tackle
      # Windup distribution
      - uses: actions/checkout@v3
        with:
          repository: windup/windup-distribution
          path: windup-distribution
      - working-directory: windup-distribution
        run: mvn install -DskipTests -Ddownstream=tackle

      # windup-web
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web
          path: windup-web
          ref: upstream-downstream-build
      - working-directory: windup-web
        run: mvn install -DskipTests -Ddownstream=tackle -s settings.xml
      # windup-keycloak-tool
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-keycloak-tool
          path: windup-keycloak-tool
          ref: upstream-downstream-build
      - working-directory: windup-keycloak-tool
        run: mvn install -DskipTests -Ddownstream=tackle
      # windup-web-keycloak-theme
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web-keycloak-theme
          path: windup-web-keycloak-theme
          ref: WINDUP-3363
      - working-directory: windup-web-keycloak-theme
        run: mvn install -DskipTests -Ddownstream=tackle
      # windup-openshift
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-openshift
          path: windup-openshift
          ref: upstream-downstream-build
      - working-directory: windup-openshift
        run: mvn install -DskipTests -Ddownstream=tackle
      # windup-web-distribution
      - uses: actions/checkout@v3
        with:
          repository: carlosthe19916/windup-web-distribution
          path: windup-web-distribution
          ref: upstream-downstream-build
      - working-directory: windup-web-distribution
        run: mvn install -DskipTests -Ddownstream=tackle

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: windup-web-distribution
          path: windup-web-distribution/target/*.zip
